### ISSUE TITLE
As a community member I want to know general information about various pests

### ISSUE THREAD

**Issue by HeatherMallalieu** [f22-black-1/f22-black-1#22]

**Comment by brrburt** [comment]
There doesn't seem to be a specific place where a user can find pest information, but if there were to be one it would make sense if it was in the expanded discussion view, since every thread is tied to a pest.

One way to implement this story would be to add a button to each expanded discussion thread that displays a pop up showing all of the pest's information (name, severity, description, etc). Implementing this would also close stories #23 and #24. 

Tasks:
- [ ] Add icon/button to expanded discussion view
- [ ] Create mat-dialog that displays when icon/button is clicked
- [ ] Populate mat-dialog with pest info
